language: r
pandoc_version: 1.19.2.1
sudo: required
cache: packages
warnings_are_errors: true
r_check_args: --as-cran
r_check_revdep: false
r:
  - 3.2
  - oldrel
  - release
  - devel

r_packages:
  - covr
after_success:
  - Rscript -e 'library(covr); codecov()'
